(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[322,0,113,120],[93,102,78,42],[437,0,75,74],[0,102,91,38],[0,0,320,100]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.largemobileholidaymainscinnamonbunstwo = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.largemobileholidaymainscranberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.largemobileholidaymainsgreens = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.largemobileholidaymainspotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.largemobileholidaymainstable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.wellmakeuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgkAqQgPgQAAgYQAAgZAQgRQARgRAYAAQAVAAANAMQAMAMAAAVQAAAHgCACQgCADgHAAIgrAAQgDAAgDgCQgCgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQADgBADAAIAXAAIAFgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgLgGgIQgIgHgKAAQgNAAgGAMQgGALAAARQgBAQAKANQAIANANAAQAJAAAGgCQAFgCAFgEIAFgDQAFgEAEAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgXAAgRgQg");
	this.shape.setTransform(42.2,2.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AAlBSIgFgBQgFgCgLgNIgFgGIgBgDQgbgjgCAAIgCABIAAAFIAAAFIAAAXQABAHACACIAGADQAFACAAAEQABAFgHACQgFABgPAAQgQAAgGgCQgFgBgBgFQABgEAFgCIADgBQADgCABgFQACgGAAgNIAAgOIgBgRIAAgNIgBgqQAAgKgCgCQgBgBgGgCIgDgBIgEgCIgBgDQAAgDACgCQACgCAJgCIAPgEIALgCQAEAAAAACQACACAAAFIgBAWIAAAdIAAAbIAAAGQAAAAABAAQAAABAAAAQAAAAAAAAQABAAAAAAIAEgDIAIgGIALgKQADgEAAgBQAAgBgFgCQgCgDAAgDQAAgFAEgCQAGgCAQAAQALAAAEACQAGACgBAEQABAGgJACQgIACgDACIgOALIgCACIgDAEIgBACQAAACAKANIABABIATAYQAHAJAFADIAKAFQAHACAAAEQAAAFgFACQgFACgMAAg");
	this.shape_1.setTransform(30.5,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AAUA0IgGgFIgFACQgNAKgOAAQgQAAgKgKQgKgJAAgQQAAgSANgJQANgKAXAAQAFAAADACQADABAAAFQAAAFgIAAQgKAAgHAFQgHAGAAAKQAAAIAGAFQAGAGAKAAQAKAAAEgFQAFgFAAgMIAAgpQAAgKgEgFQgFgGgHAAQgFAAgFADQgFACgEAGIgCADQgHAIgIAAQgEAAgDgDQgCgDAAgEQAAgLANgHQANgIAUABQALAAAJADQAJADAFAGQAEAEABAIQABAGAAAQIAAAjIABAKQABABAAAAQAAABABAAQAAABABAAQAAAAABABIADABQAHACAAADQAAAGgHAEQgIAEgKABQgFAAgFgHg");
	this.shape_2.setTransform(18,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AAqBPQgHgCABgFQgBgEAIgDIAEgDQADgBAAgFIABgUIAAgGIAAgvIgBgcIgOAlQggBVgIAAQgDAAgHgMQgGgLgPglIgZg3IgBArIgBAeIABAVQABAFACABIAFADQAGACABAFQAAAFgGACQgGACgNAAQgMAAgGgCQgGgCAAgFQABgEAFgDQAGgDABgCQABgFACgdQACgcAAgjIAAgEIgBgQQgBgEgCgBIgGgDQgHgCAAgFQAAgEAFgCQAFgCAQAAIAQABIAFABQACABAIAUIAGAQIAEAIQAaBCACAAQADAAAJgYQALgXANgnIACgHQAEgMAEgEQACgCAEgBIAQgBQAOAAAGACQAEACAAAEQABAFgHACIgDABQgDACgBAFQgBAEAAARIABA/QABAdAAAEQABADAGABIACABIAEADQAAABABAAQAAAAAAABQAAAAAAABQABABAAAAQAAAFgHACQgGACgTAAQgQAAgGgCg");
	this.shape_3.setTransform(1.8,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgSBQQgGgBAAgFQAAgEAFgCIAGgDQACgCAAgGIABgXIAAgRIAAgUIAAgJQAAgcgBgIQgBgIgCgCIgHgCQgHgCAAgEQAAgDACgCQACgCAIgCIAPgEIALgCQADAAABACQACACAAAFIAAAJQgCAoAAAoIABAmQABAIACACIAGADQAFACAAAEQAAAFgGACQgFABgPAAQgQAAgFgCg");
	this.shape_4.setTransform(-17.8,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgSBQQgGgBAAgFQAAgEAFgCIAGgDQACgCAAgGIABgXIAAgRIAAgUIAAgJQAAgcgBgIQgBgIgCgCIgHgCQgHgCAAgEQAAgDACgCQACgCAIgCIAPgEIALgCQADAAABACQACACAAAFIAAAJQgCAoAAAoIABAmQABAIACACIAGADQAFACAAAEQAAAFgGACQgFABgPAAQgQAAgFgCg");
	this.shape_5.setTransform(-24.1,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgBAhIgIgxIAAgCIAAgCQAAgFACgDQADgDAEAAQAFAAADADQACADAAAFIAAACIAAACIgIAxg");
	this.shape_6.setTransform(-28.9,-4.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgkAqQgQgQAAgYQAAgZARgRQAQgRAZAAQAWAAAMAMQAMAMAAAVQAAAHgBACQgDADgHAAIgrAAQgEAAgCgCQgCgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQACgBAEAAIAWAAIAGgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgLgIgIQgHgHgKAAQgNAAgGAMQgHALABARQAAAQAJANQAIANANAAQAJAAAGgCQAFgCAGgEIADgDQAHgEACAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgYAAgQgQg");
	this.shape_7.setTransform(-36.7,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AAPAnIgXg9IgMgeQgEgJgEgDIgHgDQgFgCAAgEQAAgFAFgBQAFgCAWAAQAUAAAFACQAFABAAAFQAAAEgIADIgBABIgEACIgBAEQAAAEAFAQIASAwIAIASQADAEABAAQACAAACgDIAIgRIACgEQAXg3AAgHQAAgEgCgCIgFgEIgDgBQgGgDAAgEQAAgFAEgBQAFgCASAAQASAAAEACQAFABAAAFQAAAEgHADIgFACQgHAFgPAnIgJAWIgWA1IgEAKQgGARgFAAQgGAAgRgrgAgtBJIgCgDQgOgfgWg5IgKgbIgHgOQgDgEgDgCIgEgBQgHgDAAgEQAAgFAGgBQAFgCAVAAQAVAAAFACQAFABAAAFQAAAEgIADIgBABIgEACQAAABAAAAQgBAAAAABQAAAAAAABQAAABAAAAQAAAEAEANIATAxIAJAUQACAEACAAQACAAACgFIAGgNQACgHAGAAQAHAAAAAHIgBAHIgPAkIgDAIQgHASgEAAQgEAAgEgJg");
	this.shape_8.setTransform(-54.2,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakeuse, new cjs.Rectangle(-67.7,-15.3,135.5,30.6), null);


(lib.wellmakethefeastuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgLALQgEgEAAgHQAAgGAEgFQAFgEAGgBQAHABAFAEQAFAFAAAGQAAAHgFAEQgFAGgHAAQgGAAgFgGg");
	this.shape.setTransform(40.7,18);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgFBAQgFgCgEgDQgEgDgBgHQgCgGAAgPIAAg4IgKAAIgDgBIAAgDIAAgDQgBgDALgKIAFgEIAEgDQALgKAEAAIACABIABACIAAAUIAZAAIADABIABAFIAAACQAAABAAAAQAAABAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAIgXAAIgBABIgBACIAAA0QAAANACAEQADAEAGgBIAJgBIAHgCQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQABABAAAAQgBAGgIAGQgKAFgLAAQgGAAgFgCg");
	this.shape_1.setTransform(34.1,13);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgHA3IgMgBIgCABIgEABIgCgBIgDgBQgDgDgDgIQgDgJAAgIQAAgEACgCQABgCAEAAQAEAAAFAIIAEAHQADAEAGACQAGADAFAAQAHAAAEgEQAEgDAAgGQAAgJgRgJIgGgDQgRgIgGgGQgFgHgBgKQABgOAJgIQAKgKAPABIAHAAIAIABIAFgBIADgBQAGAAAEAIQAFAJAAAJQAAADgCADQAAABAAAAQgBAAAAAAQgBABgBAAQAAAAgBAAQgDAAgCgCQgCgCgDgFQgEgHgFgCQgEgDgGAAQgFAAgEAEQgEADAAAGQAAAFAEADQAEAEAMAHIACAAQAdAOAAARQAAAPgLAKQgMAKgRAAg");
	this.shape_2.setTransform(25.6,14);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AATAyIgFgFIgGACQgMAJgNAAQgPAAgKgJQgKgJAAgPQAAgRANgJQAMgJAWAAQAFAAACABQAEACAAAEQgBAFgGAAQgLAAgGAGQgHAFAAAJQAAAIAGAFQAFAFAKAAQAJAAAFgEQAEgFAAgLIAAgoQAAgJgEgFQgEgFgGAAQgGAAgEACQgFACgEAFIgCADQgHAIgHAAQgEAAgDgCQgDgDAAgFQAAgKANgHQAMgHAUAAQALAAAIAEQAJADAFAGQADAEABAGQABAHAAAPIAAAiIACAJQAAAAAAABQAAABABAAQAAABABAAQAAAAABAAIADABQAHACAAADQAAAGgIAEQgGAEgKAAQgFAAgFgGg");
	this.shape_3.setTransform(15.5,14);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgiAoQgPgPAAgXQAAgYAPgQQAQgRAYAAQAUAAAMAMQAMAMAAAUQAAAGgCADQgCACgIAAIgoAAQgDAAgDgCQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQADgCADAAIAVAAIAGAAIABgEQAAgKgHgHQgHgHgJAAQgMAAgHALQgFALgBAQQAAAQAJAMQAJAMAMAAQAIAAAFgCQAGgCAFgDIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAACgCAEIgIAHQgIAIgKADQgIAEgKAAQgWAAgPgQg");
	this.shape_4.setTransform(4,14);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("Ag1BMQgGgBAAgFQAAgEAFgDIAHgDQACgDAAgQIABgpIgBgnQgBgQgBgCQgBgBgGgDQgFgCAAgFQAAgEAFgBQAFgCASAAIBAAAIALgBIAGgBIACABIACABIAEAMQACAHAAAFQAAAFgBACQgCADgDAAQgEAAgFgHIgDgFQgCgEgFgBQgFgCgHAAIgOAAIgPABQgFABgCADQgCACgBAHIgBAUIAAAJQAAAFABABIAEABIARAAQAIAAAEgCQADgCABgHIAAgCQACgLAGAAQAEAAACAGQACAFAAAVQAAATgCAGQgCAGgEAAQgGAAgCgLIAAgCQgBgHgDgCQgEgDgIAAIgRAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBABAAAAQgBACAAAHIAAAIIABAeQABAGACACIAEACQAHADAAAEQAAAFgGABQgGACgRAAQgRAAgFgCg");
	this.shape_5.setTransform(-7.9,11.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgiAoQgPgPAAgXQAAgYAQgQQAPgRAXAAQAVAAAMAMQAMAMAAAUQAAAGgCADQgCACgIAAIgoAAQgDAAgCgCQgBgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAgBQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABAAQACgCADAAIAWAAIAFAAIABgEQAAgKgGgHQgIgHgJAAQgNAAgFALQgHALAAAQQAAAQAJAMQAIAMANAAQAIAAAFgCQAGgCAFgDIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABQABACgDAEIgIAHQgJAIgJADQgIAEgKAAQgWAAgPgQg");
	this.shape_6.setTransform(-26,14);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AAOBNQgEgCAAgEQgBgEAGgCIAEgCQACgBABgFIABgQQAAgigEgIQgEgJgMAAQgEAAgFAEQgGADgCAFQgDAFgBAIIgBAdIABAOQABAEACABIAEACQAFACABAEQAAAEgGACQgFABgOAAQgRAAgEgBQgGgCAAgFQAAgDAGgCIACgCQADgBACgFIABgQIAAgRIAAgQIgBgwQgBgMgCgCQgBgCgGgBQgGgCAAgEQAAgDACgCQADgCAJgDIAMgDIAJgBQADAAACACQABACAAAEIAAAFIgBAqIAAAGIABACIACABIACgCIADgFQAGgFAGgCQAFgDAHAAQASAAAJAMQAJAMAAAXIAAAKIAAATIAAAGIABAIIAEADIADACQAFABAAAEQAAAFgFACQgFABgRAAQgOAAgGgBg");
	this.shape_7.setTransform(-38.1,11.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgFBAQgFgCgEgDQgEgDgCgHQgBgGAAgPIAAg4IgKAAIgDgBIAAgDIAAgDQAAgDALgKIAEgEIAEgDQALgKAEAAIADABIAAACIAAAUIAZAAIADABIABAFIAAACQAAABAAAAQAAABAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAIgXAAIgBABIgBACIAAA0QAAANACAEQADAEAGgBIAJgBIAHgCQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQABABAAAAQgBAGgIAGQgJAFgMAAQgGAAgFgCg");
	this.shape_8.setTransform(-48,13);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgiAoQgPgPAAgXQAAgYAPgQQAQgRAYAAQAUAAAMAMQAMAMAAAUQAAAGgCADQgCACgIAAIgoAAQgEAAgCgCQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQACgCAEAAIAVAAIAGAAIABgEQAAgKgHgHQgGgHgKAAQgMAAgHALQgFALAAAQQgBAQAJAMQAJAMAMAAQAIAAAGgCQAFgCAFgDIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAACgDAEIgHAHQgKAIgIADQgJAEgKAAQgWAAgPgQg");
	this.shape_9.setTransform(51,-9.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAjBOIgFgBQgEgBgLgOIgEgFIgCgDQgZghgCAAIgCABIgBAEIAAAGIABAVQABAHACACIAFADQAGACAAAEQAAAEgGACQgFACgOgBQgRABgEgCQgGgCAAgFQAAgEAGgBIACgCQADgBACgFIABgRIAAgOIAAgRIAAgMIgBgnQgBgLgCgCIgFgCIgEgBIgEgCIgBgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQACgCAHgDIAPgEIALgBQABAAABAAQAAAAABAAQAAAAABABQAAAAAAABQACABAAAGIgBAUIgBAcIAAAaIABAGQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAEgDIAIgGIAKgKIACgFQAAgBgEgCQgCgCAAgDQgBgFAFgCQAFgBAQgBQAKABAEABQAFACABAEQgBAFgHACIgLAEIgOALIgBACIgDADIgCACQAAADAJAMIACABIASAXQAIAIAEADIAKAEQAGADAAAEQAAAFgFACQgFABgMAAg");
	this.shape_10.setTransform(39.8,-11.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AATAyIgGgFIgFACQgMAJgNAAQgPAAgKgJQgKgJAAgPQAAgRANgJQAMgJAWAAQAFAAADABQACACAAAEQABAFgIAAQgKAAgHAGQgGAFAAAJQAAAIAGAFQAGAFAJAAQAKAAAEgEQAEgFAAgLIAAgoQAAgJgEgFQgEgFgHAAQgFAAgFACQgEACgEAFIgDADQgGAIgHAAQgEAAgCgCQgDgDgBgFQAAgKANgHQAMgHAUAAQALAAAJAEQAIADAEAGQAEAEABAGQABAHABAPIAAAiIABAJQAAABAAAAQAAABABAAQAAABABAAQAAAAAAAAIAEABQAHACAAADQAAAGgHAEQgIAEgJAAQgFAAgFgGg");
	this.shape_11.setTransform(27.9,-9.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AAoBLQgGgBAAgFQAAgFAHgCIAEgCQACgCABgFQABgFAAgOIAAgGIAAgsIgBgbIgNAjQggBRgGAAQgDABgHgMIgVgtIgXg1IgBApIAAAdIAAATQABAFACACIAEACQAHACAAAFQAAAEgFACQgGACgNAAQgMAAgFgCQgFgCAAgEQAAgEAGgDQAFgDABgCQABgFACgbQACgbAAgiIAAgDQAAgLgBgEQgBgEgDgCIgFgCQgHgCAAgFQAAgEAFgBQAFgCAQAAIAPAAIAEABQACABAIAUIAGAPIADAHQAaBAABAAQACAAAKgYQAJgVAOgmIACgGQAEgMADgDQACgCAEgBIAOgBQAPAAAFACQAEABAAAEQAAAFgGACIgDABQgDACgBAEQgBAFAAAPIABA9IACAfQABADAFACIACAAIAEADQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAFgGABQgGACgRAAQgQAAgGgCg");
	this.shape_12.setTransform(12.4,-11.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgRBNQgFgCAAgFQAAgDAEgCIAFgDQACgCABgGIABgVIAAgRIAAgTIAAgJQAAgagBgIQgBgIgDgBIgGgCQgHgCAAgEQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQACgCAIgDIAOgEIAKgBQABAAABAAQABAAAAAAQABAAAAABQAAAAABABQABABAAAGIAAAIQgBAmAAAmIABAkQAAAIACACIAGADQAFACAAAEQAAAEgFACQgGACgOgBQgPABgFgCg");
	this.shape_13.setTransform(-6.2,-11.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AgRBNQgFgCAAgFQAAgDAEgCIAFgDQACgCABgGIABgVIAAgRIAAgTIAAgJQAAgagBgIQgBgIgDgBIgGgCQgHgCAAgEQAAgBAAAAQABgBAAAAQAAgBAAAAQABgBAAAAQACgCAIgDIAOgEIAKgBQABAAABAAQABAAAAAAQABAAAAABQABAAAAABQABABAAAGIAAAIQgBAmAAAmIABAkQAAAIACACIAGADQAFACAAAEQAAAEgFACQgGACgOgBQgPABgFgCg");
	this.shape_14.setTransform(-12.2,-11.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AgBAfIgHguIgBgCIAAgCQAAgFADgDQACgDAEAAQAFAAACADQADACAAAGIAAACIAAADIgIAtg");
	this.shape_15.setTransform(-16.8,-15.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AgiAoQgPgPAAgXQAAgYAPgQQAQgRAYAAQAUAAAMAMQAMAMAAAUQAAAGgCADQgCACgIAAIgoAAQgEAAgCgCQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQACgCAEAAIAVAAIAGAAIABgEQAAgKgHgHQgGgHgKAAQgMAAgHALQgFALAAAQQgBAQAJAMQAJAMAMAAQAIAAAFgCQAGgCAFgDIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAACgDAEIgIAHQgIAIgKADQgIAEgKAAQgWAAgPgQg");
	this.shape_16.setTransform(-24.2,-9.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AAPAmIgXg8IgKgcQgFgJgEgCIgGgDQgFgCAAgEQAAgEAFgCQAEgBAVgBQATABAFABQAFACAAAEQAAAEgIADIgBABIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAADAFAPIASAuIAHASQADAEACAAQABAAACgEIAHgPIACgFQAWg0AAgHQAAgDgCgDQgBgCgDgBIgDgBQgGgDAAgEQgBgEAFgCQAEgBASgBQAQABAFABQAFACAAAEQAAAEgHADIgFACQgGAFgPAkIgJAWIgUAyIgEAKQgHAQgEAAQgGAAgPgogAgsBFIgBgDQgNgegWg1IgJgaIgHgNQgCgEgDgCIgEgBQgGgDAAgEQAAgEAEgCQAFgBAVgBQAUABAFABQAFACAAAEQAAAEgJAEIAAAAIgEACIgBAEQAAADAEANIASAuIAIAUQACAEADAAQABAAACgGIAGgMQACgHAGAAQAGAAAAAHIgBAHIgNAiIgEAIQgHARgEAAQgEAAgEgJg");
	this.shape_17.setTransform(-40.9,-11.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakethefeastuse, new cjs.Rectangle(-53.9,-26.4,118.6,52.7), null);


(lib.wellmakethefeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgEAFQgCgCAAgDQAAAAAAAAQAAgBABgBQAAAAAAgBQABAAAAgBQABAAAAgBQABAAAAAAQABgBABAAQAAAAAAAAQADAAACACQAAABABAAQAAABAAAAQAAABABABQAAAAAAAAQAAADgCACQgCACgDAAQAAAAAAAAQgBgBgBAAQAAAAgBAAQAAgBgBAAg");
	this.shape.setTransform(54.6,2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AAAAjIgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAIAAgzIgBgCIgEgBIgFAAIgFAAIgDAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgBgEIAAgCIABgCIABgCIACgBIAvAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIAAADIAAACIAAADIgBACIgCAAIgNAAIgEABIgBACIAAAzIgBABIgBABIgDABg");
	this.shape_1.setTransform(50.3,-0.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AAAAkIgBAAQgBAAgBAAQAAAAgBgBQgBAAAAAAQAAgBgBAAIAAhCIACgCIADgBIABAAIACAAQABAAABAAQABABAAAAQABAAAAABQAAAAABABIAABBIgCACIgDABg");
	this.shape_2.setTransform(46,-1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgdAjIgCgBIgBgDIAAg9IABgDIACgBIAaAAIAHABIAGACQAHACAGAFQAEAEAEAHIACAGIAAAHQAAAIgDAHIgEAFIgEAFIgGAEIgGADQgGACgHABgAgSgUIgBADIAAAkQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIACABIANAAQAEAAAFgBQAEgBADgDQADgDACgEQACgFABgFQgBgEgCgEQgCgFgDgDIgHgEQgFgCgEAAIgMAAIgDACg");
	this.shape_3.setTransform(40.8,-0.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgXAjIgCgBIgBgCIAAg/IABgCIACgBIAvAAIADACIAAACIAAACIAAACIAAADIgDABIgjAAIgCACIgBACIAAAJIABACIADABIAWAAIACABIAAADIAAACIAAABQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgVAAQgBAAAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQgBABAAAAIAAAKIABACIADABIAiAAQABABABAAQAAABAAAAQABABAAAAQAAABAAABIAAABIAAADIgBADIgCABg");
	this.shape_4.setTransform(33.5,-0.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AARAjIgBgBIgCAAIgBgBIgLgSIgCgDIgDAAIgJAAIgCABIgBACIAAARIgBACIgDABIgCAAIgCAAIgEgBIgBgDIAAg/IABgCIADAAIAcAAQAFAAAFABQAFACADADQADADACAEQACAFAAAFQAAAGgDAEIgEAFIgFADQgBABAAAAQgBAAAAABQAAAAAAABQgBAAAAAAIAAACIADAEIAFAFIADAGIABADIgBACIgCACIgCABIgCAAgAgNgWQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAIAAAQQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAIACAAIAOAAIAFAAIAFgCIACgEIABgFQAAgGgDgCIgFgDIgFAAIgOAAIgCAAg");
	this.shape_5.setTransform(26.6,-0.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgCAkIgIgDIgGgDIgFgEIgFgGIgDgFQgDgIAAgHQAAgHADgHIADgFIAFgGQAFgFAGgDIAIgCIAGAAIAIAAIAHADIAIAEIAGAFIAAACQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAAAIgEACIgCABIgBABIgDgBIgEgDIgFgEQgEgBgFAAQgEAAgEACQgEACgDADQgEAEgCAEQgCAEABAEQgBAFACAEQACAFAEADQADADAEACQAEACAEAAQAGAAAEgDQAFgCADgDIADgBIACABIACACIADABIABADIAAABIgHAFIgHAFQgDABgEABIgIABIgGAAg");
	this.shape_6.setTransform(19.1,-0.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgXAjIgCgBIgBgCIAAg/IABgCIACgBIAwAAIABACIABACIAAACIAAACIgBADIgBABIgjAAIgCACIgCACIAAAJIACACIACABIAWAAIACABIABADIAAACIAAABQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBAAIgVAAQgBAAAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQgBABAAAAIAAAKIACACIACABIAjAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAABIAAABIgBADIAAADIgBABg");
	this.shape_7.setTransform(9.5,-0.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgXAjIgDAAIgCgCIAAhBIACgCIADAAIACgBIACAAQABAAAAAAQABABABAAQAAAAAAABQABAAAAABIAAAWIABADIACABIAYAAIACgBIABgDIAAgWQABgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAIAFAAIACAAIADACIAABBQgBAAAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgEAAIgDAAIgDgCIAAgYIgBgDQAAAAAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAIgXAAIgCABIgCADIAAAYIgBACIgDAAIgCABg");
	this.shape_8.setTransform(2.2,-0.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AAAAjIgEgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAgzIAAgCIgDgBIgGAAIgFAAIgDAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIAAgEIAAgCIAAgCIABgCIACgBIAvAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABIAAADIAAACIAAADIgBACIgCAAIgOAAIgCABIgBACIAAAzIgBABIgDABIgCABg");
	this.shape_9.setTransform(-4.5,-0.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AgXAjIgCgBIgBgCIAAg/IABgCIACgBIAvAAIADACIAAACIAAACIAAACIAAADIgDABIgjAAIgCACIgBACIAAAJIABACIADABIAWAAIACABIAAADIAAACIAAABQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgVAAQgBAAAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQgBABAAAAIAAAKIABACIADABIAiAAQABABABAAQAAABAAAAQABABAAAAQAAABAAABIAAABIAAADIgBADIgCABg");
	this.shape_10.setTransform(-13.3,-0.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AAQAjIgCgBIgRgbIgDgBIgCgBIgEABQAAABgBAAQAAAAAAABQAAAAgBABQAAAAAAABIAAAVIgBACIgCABIgDABIgDAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAhBIABgBIACgBIADAAIACAAQADAAABADIAAAVQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABAAIACABQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBIATgXIABAAIACAAIACAAIADACIACABIABACIgBABIgRAUIgBACIAAACIAAABIABACIAWAeIAAAAIAAACIgBABIgCABIgDABIgCABg");
	this.shape_11.setTransform(-20,-0.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AAbAjIgCAAIgDAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAAAIgEgJIgBgDIgCAAIgXAAIgBAAIgBABIgBAAIAAACIgEAJIgBABIgCABIgCAAIgCAAIgCAAIgCAAIgCgBIgBgBIAdhBIABgCIACAAIADAAIACACIAbBBIABAAIgBACIgCAAgAAAgJIgBAAIAAACIgCADIgCAEIgBADIgCADIAAACIABABIABABIANAAIABAAIABgCIgBgDIgCgFIgDgGIgBgDIgCgBg");
	this.shape_12.setTransform(-27,-0.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AAAAjIgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAgzIAAgCIgDgBIgGAAIgFAAIgDAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgBgEIAAgCIABgCIABgCIACgBIAvAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABIAAADIAAACIAAADIgBACIgCAAIgOAAIgCABIgBACIAAAzIgBABIgDABIgCABg");
	this.shape_13.setTransform(-33.2,-0.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgLAiQgGgDgEgEQgEgDgCgGIgCgGIgBgGIAAgSIAAgTIABgCIADgBIACAAIADAAIACAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABIAAAiIABAIQABAEADADIAFAEQAEACADAAQAEAAAEgCIAFgEQADgDABgEIABgIIAAgiQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIAEgBIACAAIADAAIACACIABACIAAAlIgBAGIgCAGQgCAGgEADQgFAEgFADQgGACgGAAQgFAAgGgCg");
	this.shape_14.setTransform(-42.8,-0.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgHAkIgHgDIgGgDIgFgEQgFgGgDgGIgCgGIgBgIIABgHIACgGQADgHAFgFIAFgEIAGgEIAHgCIAHAAIAHAAIAHACQAHADAFAFQAFAFADAHQADAGAAAHIgBAIIgCAGQgDAGgFAGQgFAEgHADIgHADIgHAAIgHAAgAgIgVQgEABgEAEQgDADgCAFQgCAEAAAEQAAAFACAFIAFAHIAIAFQAEACAEAAQAFAAAEgCQAEgCADgDQAEgEACgDQACgFAAgFQAAgEgCgEQgCgFgEgDQgDgEgEgBQgEgCgFAAQgEAAgEACg");
	this.shape_15.setTransform(-50.7,-0.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AgCAkIgCAAIgBgBIgBgCIAAgYIAAgEIgCgEIgUgdIAAgBIABgCIACgCIADgBIACgBIACABIACABIAOAXIABABIABAAIABAAIACgBIANgXIACgCIADAAIACAAIACABIADACIABACIgBABIAAABIgUAeIgBAEIgBABIAAACIAAAYQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAIgEAAg");
	this.shape_16.setTransform(-57.9,-1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakethefeast, new cjs.Rectangle(-63.1,-7.7,121.3,14.1), null);


(lib.theturkeyuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAEgFAHAAQAHAAAFAFQAGAFgBAGQABAHgGAFQgFAFgHAAQgHAAgEgFg");
	this.shape.setTransform(55.4,6.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgzBKQgFgFAAgHQAAgFAEgEQAEgEAFAAIAFAAIAEADIADAEQADAEACAAQAFAAAGgIQAGgIAAgJQAAgJgIgSIgBgDIgSgmIgKgWQgCgEgHgDQgEgBgBgCQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgFAGgCQAGgCAQAAQAQAAAGACQAFACAAAFIAAADIgCACIgFACQgEACAAACIACAIIAJAWIAJAVQADAGABAAQABAAADgGIAHgRIAJgWIACgLQAAgDgGgEQgGgDAAgDQAAgEAFgCQAFgCAMAAQAOAAAFACQAEACAAAFQAAAEgGABIgFACQgGADgHATIgDAJIgPAjQgSAugLAPQgMAOgQAAQgIAAgGgFg");
	this.shape_1.setTransform(46.8,4.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgkAqQgQgQAAgYQAAgZARgRQAQgRAZAAQAWAAAMAMQAMAMABAVQAAAHgCACQgDADgHAAIgrAAQgEAAgCgCQgCgCABgDQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQACgBAEAAIAWAAIAGgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgLgIgIQgHgHgKAAQgNAAgGAMQgHALABARQAAAQAJANQAIANANAAQAJAAAGgCQAFgCAGgEIADgDQAHgEACAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgYAAgQgQg");
	this.shape_2.setTransform(35.3,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AAlBSIgFgBQgFgCgLgNIgEgGIgCgDQgbgjgCAAIgCABIAAAFIAAAFIAAAXQABAHACACIAGADQAFACABAEQAAAFgHACQgFABgOAAQgRAAgGgCQgGgBABgFQgBgEAGgCIADgBQADgCABgFQABgGAAgNIAAgOIAAgRIAAgNIgBgqQAAgKgCgCQgBgBgGgCIgDgBIgEgCIgBgDQAAgDACgCQACgCAJgCIAOgEIAMgCQADAAABACQACACAAAFIgBAWIAAAdIAAAbIAAAGQAAAAABAAQAAABAAAAQAAAAAAAAQABAAAAAAIAFgDIAIgGIAKgKQADgEAAgBQAAgBgEgCQgDgDgBgDQABgFAEgCQAGgCAQAAQALAAAEACQAGACAAAEQgBAGgHACQgJACgDACIgOALIgBACIgFAEIgBACQABACAJANIACABIATAYQAHAJAFADIAKAFQAHACAAAEQAAAFgFACQgGACgMAAg");
	this.shape_3.setTransform(23.5,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AghA3QgFgBAAgFQAAgEAFgCIADgBQADgCABgEIABgMIAAgHIAAgJIAAgHQAAgUgBgGQgBgGgCgCIgGgBQgGgDAAgDQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABgBIAHgEIAPgFIAKgCQAGAAABAPIAAADIAAAAQAGgJAHgFQAFgEAHAAQAIAAAEAEQAFAFAAAIQAAAIgDAEQgEAFgHAAIgFgBIgFgEIgDgEQAAgBAAgBQAAAAAAgBQgBAAAAAAQAAAAAAAAQgJAAgCALQgDAKAAAhQAAAKABAFQABAFADABIAEACQAIACgBAEQAAAFgGABQgGACgPAAQgRAAgFgCg");
	this.shape_4.setTransform(12.9,2.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AAYA5QgBgCAAgEIAAgIIAAAAIgBgBQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAIgCACQgGAGgGACQgGADgIAAQgJAAgHgDQgHgEgGgFQgFgHgCgIQgCgKAAgXIAAgHIAAgJIAAgCQAAgJgBgCQgBgDgEgCIgFgBQgHgBAAgEQAAgEADgBQACgCAIgDIAPgEIAMgBQABAAAAAAQABAAABAAQAAAAABABQAAAAAAAAQACADAAAFIgBAEIgBAqQABAWAFAJQAEAIALABQANAAAFgMQAGgLgBgaIAAgJQAAgJgBgCQgBgDgEgCIgFgBQgFgBgBgEQAAgBABgBQAAgBAAAAQAAgBABAAQAAgBABAAQABgCAJgDIAOgEIAMgBQADAAACABQABACAAAGIAAAGIgBAuIAAASIAAAIQABAEAGACIAAAAIACABQAHACgBAEQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAABQgCABgFACIgQAGIgMACQgBAAAAgBQgBAAgBAAQAAAAgBgBQAAAAgBAAg");
	this.shape_5.setTransform(1.6,2.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgWBQQgHgCAAgFQAAgFAGgCQAGgCABgCQABgCABgSIABg0IAAgeIgBgSQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAIgGgBIgFAAQgIAAgEACQgFACgDAFIgDAHIgEAIIgCADIgFABQgDAAgBgCQgCgDAAgHQAAgPADgKQAEgJAFAAIABAAQAKACANAAIBBAAQAOAAAJgCIABAAQAFAAAEAJQADAKAAAPQAAAGgBADQgCADgEAAIgDgBIgDgDIgEgIIgDgHQgDgFgFgCQgEgCgIAAIgFAAIgGABQgCABgBAEIgBARIAAAeIABA0QABASABACQABACAGACQAGACAAAFQAAAFgHACQgFABgSAAQgQAAgGgBg");
	this.shape_6.setTransform(-12.2,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgkAqQgPgQAAgYQAAgZAQgRQARgRAYAAQAVAAANAMQAMAMAAAVQAAAHgCACQgCADgHAAIgrAAQgDAAgDgCQgCgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQADgBADAAIAXAAIAFgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgLgGgIQgIgHgKAAQgNAAgGAMQgGALAAARQgBAQAKANQAIANANAAQAJAAAGgCQAFgCAFgEIAFgDQAFgEAEAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgXAAgRgQg");
	this.shape_7.setTransform(-31.6,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AAQBQQgGgBAAgFQAAgEAGgCIAEgCQACgCACgEIABgRQAAgkgFgIQgFgJgLAAQgFAAgGAEQgFADgDAGQgDAEgBAIIAAAfIAAAPQABAEADABIAEACQAGACAAAEQAAAFgGABQgFACgPAAQgRAAgGgCQgFgBAAgFQAAgEAFgCIADgBQADgCACgFIABgRIAAgSIAAgRIgBgyQgBgNgBgCQgCgBgGgCQgHgCAAgEQAAgDADgCIANgGIALgDIAKgBQAEAAABACQACACAAAFIAAAFIgBAtIAAAFIAAADIACABIACgDIAEgFQAGgFAGgDQAGgDAHABQATAAAJAMQAKANAAAXIAAALIAAAUIAAAHQAAAFABACQABADADACIACABQAGABAAAFQAAAFgFABQgGACgRAAQgPAAgFgCg");
	this.shape_8.setTransform(-44.3,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgFBEQgGgCgEgEQgEgEgBgGQgCgGAAgRIAAg7IgKAAIgDgBIgBgDIAAgDQAAgDALgKIAFgEIAEgEQAMgKAEAAIADABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAUIAZAAIAEABQAAABAAAAQAAABABAAQAAABAAAAQAAABAAABIAAACIgBAFQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgXAAIgCABIAAACIAAA3QAAAPACADQACAEAHAAQAEAAAFgCIAIgCQAAAAABAAQABAAAAAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAFgJAGQgKAGgMAAQgGAAgFgBg");
	this.shape_9.setTransform(-54.7,1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.theturkeyuse, new cjs.Rectangle(-60.7,-15.3,121.4,30.6), null);


(lib.thestuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAEgFAHAAQAHAAAGAFQAEAFAAAGQAAAHgEAFQgGAFgHAAQgHAAgEgFg");
	this.shape.setTransform(58.7,6.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgpBJQgOgJAAgMQAAgGADgDQADgEAGAAQAFAAADADQACACACAFQACAJAHAEQAIAFANAAQAOAAAKgGQAKgGAAgIQAAgFgEgDQgEgDgGAAIgNABIgRABQgUAAgKgHQgLgHAAgJQAAgFAEgGQAEgEAIgFQgHgGgDgHQgDgHAAgJQAAgSANgMQAOgMAVAAIALABIARADQAEAAAFgCIAMgHIAEAEIABADQAAAFgEAFQgDAEgHADIAEAJIABAKQAAASgOAMQgNAKgVAAIgMAAIgLgCIgDAEIgBAEQAAAFAFADQAFACALAAIAQgBIASgBQAPAAAJAGQAIAGAAAMQAAASgSAMQgRAMgaAAQgVAAgPgJgAgRg3QgGAHAAALQAAAMAFAHQAGAHAJAAQAJAAAGgHQAGgHAAgLQAAgMgGgHQgGgHgJAAQgIAAgGAHg");
	this.shape_1.setTransform(50.1,4.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AAPA3QgGgBABgFQgBgEAGgCIAEgCQADgBABgFIABgRQAAgjgEgJQgFgJgMAAQgFAAgFAEQgGADgDAHQgCAEgBAJIgBAeQAAALABADQAAAEADABIAEACQAGACAAAEQAAAFgGACQgFABgPAAQgQAAgGgCQgGgBAAgFQAAgEAGgCIADgBQACgCABgEQACgDAAgJIgBgHIAAgJIAAgLIAAgXQgBgFgCgCIgGgBQgGgDAAgDQAAgDACgCIAHgEIAQgFIAMgCQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQABABAAAEIAAAIIAAABIABAAIABAAIADgDIACgCQANgLAMAAQAJAAAHADQAIAEAEAGQAGAGACAIQACAJAAASIAAAOIAAAHIAAAHIABALQABADADACIADABQAFACABAEQgBAFgFABQgFACgRAAQgQAAgFgCg");
	this.shape_2.setTransform(37.1,2.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AgTBQQgGgCAAgFQAAgEAGgCIADgBQADgBABgEQABgEAAgIIAAgIIAAgJIAAgMIgBgWQgBgFgCgBIgFgCQgHgCAAgEQAAgCACgCIAHgEIARgGIALgCQAAAAABAAQABABAAAAQABAAAAAAQABABAAAAIABAIIAAAGIAAAFIgBAcIAAABIAAAbIABAPQABAFACABIAEACQAGACAAAEQAAAEgFACQgGACgOAAQgQAAgGgCgAgNg3QgFgEAAgGQAAgHAGgEQAFgFAHAAQAHAAAFAFQAEAEAAAGQAAAGgFAEQgFAEgHAAQgHAAgFgDg");
	this.shape_3.setTransform(27.2,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgfBQQgFgBAAgFQAAgEAFgCIADgBQADgCABgDIABgNIAAgLIAAg1IgNAAIgDgBIgBgFIAAgCIABgEQAAAAABgBQAAAAAAAAQABAAABAAQAAgBABAAIALAAIgBgIIAAgIQAAgRAKgKQAKgJASAAQANAAAIAFQAHAGAAAJQAAAGgCADQgDACgGAAQgDAAgDgBIgFgFIgCgEQgEgIgHAAQgEAAgCACQgCADAAAFIACAMQACAKAAAHIARAAIADABQABABAAAAQAAABAAAAQAAABAAAAQAAABAAABIAAACIgBAFQAAAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgQAAIAAA4IAAATQABAFADABIAEACQAHACAAAEQAAAFgGABQgFACgQAAQgQAAgGgCg");
	this.shape_4.setTransform(21.9,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgfBQQgFgBAAgFQAAgEAFgCIADgBQADgCABgDIABgNIAAgLIAAg1IgNAAIgDgBIgBgFIAAgCIABgEQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAIALAAIgBgIIAAgIQAAgRAKgKQAKgJASAAQANAAAIAFQAHAGAAAJQAAAGgCADQgDACgGAAQgDAAgDgBIgFgFIgCgEQgEgIgHAAQgEAAgCACQgCADAAAFIACAMQACAKAAAHIARAAIADABQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABIAAACIgBAFQAAAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgQAAIAAA4IAAATQABAFADABIAEACQAHACAAAEQAAAFgGABQgFACgQAAQgQAAgGgCg");
	this.shape_5.setTransform(15.5,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AAZA5QgCgCAAgEIAAgIIAAAAIAAgBQgCAAgDADIgBACQgFAGgHACQgGADgJAAQgIAAgHgDQgIgEgEgFQgFgHgDgIQgCgKAAgXIAAgHIAAgJIAAgCQAAgJgBgCQgCgDgEgCIgEgBQgGgBAAgEQgBgEADgBQACgCAIgDIAPgEIAMgBQABAAAAAAQABAAABAAQAAAAABABQAAAAABAAQABADAAAFIAAAEIgBAqQAAAWAEAJQAFAIALABQAMAAAGgMQAFgLABgaIAAgJQgBgJgBgCQgBgDgEgCIgEgBQgHgBABgEQAAgBAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQADgCAHgDIAQgEIALgBQADAAACABQABACABAGIgBAGIgBAuIAAASIABAIQABAEAFACIABAAIACABQAFACAAAEQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBABQgCABgEACIgQAGIgMACQgBAAAAgBQgBAAgBAAQAAAAgBgBQAAAAAAAAg");
	this.shape_6.setTransform(4.7,2.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgFBEQgGgCgEgEQgEgEgBgGQgCgGAAgRIAAg7IgKAAIgDgBIgBgDIAAgDQAAgDALgKIAFgEIAEgEQAMgKAEAAIADABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAUIAZAAIAEABQAAABAAAAQAAABAAAAQABABAAAAQAAABAAABIAAACIgBAFQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgXAAIgCABIAAACIAAA3QAAAPACADQACAEAHAAQAEAAAFgCIAIgCQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAFgJAGQgKAGgMAAQgGAAgFgBg");
	this.shape_7.setTransform(-5.8,1.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgbBQQgMgCgIgFQgFgCgDgKQgCgJAAgNQAAgFABgDQACgDAEAAQAGABAFAJIACAFQAIAMAIAGQAJAGALAAQALgBAJgGQAJgHgBgLQABgQghgPIgEgBQgbgLgJgKQgIgKgBgQQAAgTAPgOQAPgNAYABIANAAIAOAEIAFgDIAEgBQACAAADACIAEAGQAFAGABAIQACAHAAAGQAAAEgBACQgCACgDAAQgGAAgGgIIgBgCQgGgJgIgEQgIgDgIAAQgNgBgGAGQgIAGAAAKQAAAJAGAHQAGAFAYALIAEACQAUAIAJAHQAGAGAEAHQADAIAAAJQgBAWgQANQgPANgcAAQgNAAgNgDg");
	this.shape_8.setTransform(-16.3,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgkAqQgQgQAAgYQABgZAQgRQARgRAYAAQAVAAANAMQAMAMAAAVQAAAHgBACQgDADgHAAIgrAAQgEAAgCgCQgCgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQACgBAEAAIAXAAIAFgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgLgGgIQgIgHgKAAQgNAAgGAMQgHALABARQAAAQAJANQAIANANAAQAJAAAGgCQAFgCAFgEIAEgDQAHgEACAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgYAAgQgQg");
	this.shape_9.setTransform(-34.8,2.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAQBQQgGgBAAgFQAAgEAGgCIAEgCQACgCACgEIABgRQAAgkgFgIQgFgJgLAAQgFAAgGAEQgFADgDAGQgDAEgBAIIAAAfIAAAPQABAEADABIAEACQAGACAAAEQAAAFgGABQgFACgPAAQgRAAgGgCQgFgBAAgFQAAgEAFgCIADgBQADgCACgFIABgRIAAgSIAAgRIgBgyQgBgNgBgCQgCgBgGgCQgHgCAAgEQAAgDADgCIANgGIALgDIAKgBQAEAAABACQACACAAAFIAAAFIgBAtIAAAFIAAADIACABIACgDIAEgFQAGgFAGgDQAGgDAHABQATAAAJAMQAKANAAAXIAAALIAAAUIAAAHQAAAFABACQABADADACIACABQAGABAAAFQAAAFgFABQgGACgRAAQgPAAgFgCg");
	this.shape_10.setTransform(-47.6,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgFBEQgGgCgEgEQgEgEgBgGQgCgGAAgRIAAg7IgKAAIgDgBIgBgDIAAgDQAAgDALgKIAFgEIAEgEQAMgKAEAAIADABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAUIAZAAIAEABQAAABAAAAQAAABABAAQAAABAAAAQAAABAAABIAAACIgBAFQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgXAAIgCABIAAACIAAA3QAAAPACADQACAEAHAAQAEAAAFgCIAIgCQAAAAABAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAFgJAGQgKAGgMAAQgGAAgFgBg");
	this.shape_11.setTransform(-57.9,1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thestuffing, new cjs.Rectangle(-63.9,-15.3,127.9,30.6), null);


(lib.thesides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAEgFAHAAQAHAAAGAFQAEAFAAAGQAAAHgEAFQgGAFgHAAQgHAAgEgFg");
	this.shape.setTransform(46.5,6.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgIA6IgLgCIgEACIgDABIgDgBIgCgBQgEgDgDgJQgDgJAAgJQAAgDACgDQACgCADAAQAFAAAFAJIAEAHQAEAEAFADQAGACAGAAQAHAAAFgDQAEgEAAgGQAAgKgSgJIgGgDQgSgJgGgGQgGgHAAgLQAAgOAKgKQAKgJAQAAIAHABIAIABIAGgCIADgBQAGAAAFAJQAFAJAAAKQAAAEgCACQgBACgEAAQgCAAgDgCIgGgIQgEgHgEgCQgFgDgGAAQgGAAgEAEQgEADAAAGQAAAFAFAEQAEAEANAHIABABQAfAOAAASQAAAQgMAKQgMALgSAAg");
	this.shape_1.setTransform(38.5,2.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgjAqQgQgQgBgYQAAgZARgRQARgRAYAAQAWAAAMAMQANAMAAAVQAAAHgCACQgDADgIAAIgqAAQgDAAgDgCQgBgCAAgDQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQADgBADAAIAWAAIAHgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgLgIgIQgHgHgKAAQgNAAgGAMQgHALAAARQABAQAIANQAKANANAAQAIAAAFgCQAGgCAGgEIADgDQAHgEACAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgDAEIgHAHQgKAIgJAEQgJADgLAAQgWAAgQgQg");
	this.shape_2.setTransform(27.9,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AgwBEQgNgPAAgZQAAgbAPgQQAPgRAYAAIAHABQAEABABACQACADAAACQAAAGgHAAIgDAAIgCAAQgNAAgHAKQgIAJAAASQAAATAIAMQAIALANAAQALAAAGgGQAHgHAAgMIAAgfIAAgyQAAgIgCgDQgBgDgEgCIgDgBQgHgCAAgEQAAgDADgCQACgCAJgDIAMgEIALgBQAEAAABACQACACAAAFIAAAGIgCBEIABAvQABALACABIAIADQAFABAAAEQAAAFgQAGIgLACIgIABQgBAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgCAAgEIAAgFIgBgCIAAgBIgEACIgFAEQgGAFgGACQgGADgHAAQgVAAgNgPg");
	this.shape_3.setTransform(15.7,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgTBQQgGgCAAgFQAAgEAGgCIADgBQADgBABgEQABgEAAgIIAAgIIAAgJIAAgMIgBgWQgBgFgCgBIgFgCQgHgCAAgEQAAgCACgCIAHgEIARgGIALgCQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAIABAIIAAAGIAAAFIgBAcIAAABIAAAbIABAPQABAFACABIAEACQAGACAAAEQAAAEgFACQgGACgOAAQgQAAgGgCgAgNg3QgFgEAAgGQAAgHAGgEQAFgFAHAAQAHAAAFAFQAEAEAAAGQAAAGgFAEQgFAEgHAAQgHAAgFgDg");
	this.shape_4.setTransform(5.5,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgbBQQgMgCgIgFQgFgCgDgKQgCgJAAgNQAAgFABgDQACgDAEAAQAGABAFAJIACAFQAIAMAIAGQAJAGALAAQALgBAJgGQAJgHgBgLQABgQghgPIgEgBQgbgLgJgKQgIgKgBgQQAAgTAPgOQAPgNAYABIANAAIAOAEIAFgDIAEgBQACAAADACIAEAGQAFAGABAIQACAHAAAGQAAAEgBACQgCACgDAAQgGAAgGgIIgBgCQgGgJgIgEQgIgDgIAAQgNgBgGAGQgIAGAAAKQAAAJAGAHQAGAFAYALIAEACQAUAIAJAHQAGAGAEAHQADAIAAAJQgBAWgQANQgPANgcAAQgNAAgNgDg");
	this.shape_5.setTransform(-4.1,0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgkAqQgQgQAAgYQABgZAQgRQARgRAYAAQAVAAANAMQAMAMAAAVQAAAHgBACQgDADgHAAIgrAAQgEAAgCgCQgCgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQACgBAEAAIAXAAIAFgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgLgGgIQgIgHgKAAQgNAAgGAMQgHALABARQAAAQAJANQAIANANAAQAJAAAGgCQAFgCAFgEIAEgDQAHgEACAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgYAAgQgQg");
	this.shape_6.setTransform(-22.7,2.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AAQBQQgGgBAAgFQAAgEAGgCIAEgCQACgCACgEIABgRQAAgkgFgIQgFgJgLAAQgFAAgGAEQgFADgDAGQgDAEgBAIIAAAfIAAAPQABAEADABIAEACQAGACAAAEQAAAFgGABQgFACgPAAQgRAAgGgCQgFgBAAgFQAAgEAFgCIADgBQADgCACgFIABgRIAAgSIAAgRIgBgyQgBgNgBgCQgCgBgGgCQgHgCAAgEQAAgDADgCIANgGIALgDIAKgBQAEAAABACQACACAAAFIAAAFIgBAtIAAAFIAAADIACABIACgDIAEgFQAGgFAGgDQAGgDAHABQATAAAJAMQAKANAAAXIAAALIAAAUIAAAHQAAAFABACQABADADACIACABQAGABAAAFQAAAFgFABQgGACgRAAQgPAAgFgCg");
	this.shape_7.setTransform(-35.4,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgFBEQgGgCgEgEQgEgEgBgGQgCgGAAgRIAAg7IgKAAIgDgBIgBgDIAAgDQAAgDALgKIAFgEIAEgEQAMgKAEAAIADABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAUIAZAAIAEABQAAABAAAAQAAABABAAQAAABAAAAQAAABAAABIAAACIgBAFQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgXAAIgCABIAAACIAAA3QAAAPACADQACAEAHAAQAEAAAFgCIAIgCQAAAAABAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAFgJAGQgKAGgMAAQgGAAgFgBg");
	this.shape_8.setTransform(-45.8,1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thesides, new cjs.Rectangle(-51.8,-15.3,103.6,30.6), null);


(lib.thedesserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAEgFAHAAQAHAAAFAFQAGAFgBAGQABAHgGAFQgFAFgHAAQgHAAgEgFg");
	this.shape.setTransform(62.6,6.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgIA6IgLgCIgEACIgDABIgDgBIgCgBQgEgDgDgJQgDgJAAgJQAAgDACgDQACgCADAAQAFAAAFAJIAEAHQAEAEAFADQAGACAGAAQAHAAAFgDQAEgEAAgGQAAgKgSgJIgGgDQgSgJgGgGQgGgHAAgLQAAgOAKgKQAKgJAQAAIAHABIAIABIAGgCIADgBQAGAAAFAJQAFAJAAAKQAAAEgCACQgBACgEAAQgCAAgDgCIgGgIQgEgHgEgCQgFgDgGAAQgGAAgEAEQgEADAAAGQAAAFAFAEQAEAEANAHIABABQAfAOAAASQAAAQgMAKQgMALgSAAg");
	this.shape_1.setTransform(54.6,2.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgFBEQgGgCgEgEQgEgEgBgGQgCgGAAgRIAAg7IgKAAIgDgBIgBgDIAAgDQAAgDALgKIAFgEIAEgEQAMgKAEAAIADABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAUIAZAAIAEABQAAABAAAAQAAABAAAAQABABAAAAQAAABAAABIAAACIgBAFQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgXAAIgCABIAAACIAAA3QAAAPACADQACAEAHAAQAEAAAFgCIAIgCQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAFgJAGQgKAGgMAAQgGAAgFgBg");
	this.shape_2.setTransform(46,1.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AghA3QgGgBABgFQgBgEAGgCIADgBQACgCACgEIABgMIAAgHIAAgJIAAgHQAAgUgBgGQgBgGgCgCIgGgBQgGgDAAgDQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABgBIAHgEIAPgFIAKgCQAFAAACAPIAAADIAAAAQAGgJAHgFQAGgEAGAAQAIAAAEAEQAFAFAAAIQAAAIgEAEQgDAFgHAAIgFgBIgFgEIgCgEQgBgBAAgBQAAAAAAgBQgBAAAAAAQAAAAAAAAQgIAAgEALQgCAKAAAhQAAAKABAFQABAFADABIAEACQAIACgBAEQAAAFgGABQgGACgOAAQgSAAgFgCg");
	this.shape_3.setTransform(38,2.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgjAqQgQgQgBgYQAAgZARgRQAQgRAZAAQAWAAAMAMQANAMAAAVQAAAHgCACQgCADgIAAIgrAAQgEAAgCgCQgBgCAAgDQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQACgBAEAAIAWAAIAGgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgLgIgIQgHgHgKAAQgNAAgGAMQgHALAAARQABAQAIANQAKANANAAQAIAAAGgCQAFgCAGgEIADgDQAHgEACAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgLAAQgWAAgQgQg");
	this.shape_4.setTransform(27.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgIA6IgLgCIgEACIgDABIgDgBIgCgBQgEgDgDgJQgDgJAAgJQAAgDACgDQACgCADAAQAFAAAFAJIAEAHQAEAEAFADQAGACAGAAQAHAAAFgDQAEgEAAgGQAAgKgSgJIgGgDQgSgJgGgGQgGgHAAgLQAAgOAKgKQAKgJAQAAIAHABIAIABIAGgCIADgBQAGAAAFAJQAFAJAAAKQAAAEgCACQgBACgEAAQgCAAgDgCIgGgIQgEgHgEgCQgFgDgGAAQgGAAgEAEQgEADAAAGQAAAFAFAEQAEAEANAHIABABQAfAOAAASQAAAQgMAKQgMALgSAAg");
	this.shape_5.setTransform(16.7,2.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgIA6IgLgCIgEACIgDABIgDgBIgCgBQgEgDgDgJQgDgJAAgJQAAgDACgDQACgCADAAQAFAAAFAJIAEAHQAEAEAFADQAGACAGAAQAHAAAFgDQAEgEAAgGQAAgKgSgJIgGgDQgSgJgGgGQgGgHAAgLQAAgOAKgKQAKgJAQAAIAHABIAIABIAGgCIADgBQAGAAAFAJQAFAJAAAKQAAAEgCACQgBACgEAAQgCAAgDgCIgGgIQgEgHgEgCQgFgDgGAAQgGAAgEAEQgEADAAAGQAAAFAFAEQAEAEANAHIABABQAfAOAAASQAAAQgMAKQgMALgSAAg");
	this.shape_6.setTransform(7.1,2.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgkAqQgPgQAAgYQAAgZAQgRQAQgRAZAAQAWAAAMAMQAMAMAAAVQAAAHgCACQgBADgJAAIgqAAQgEAAgBgCQgDgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABgBQABgBAEAAIAXAAIAFgBQABAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQgBgLgGgIQgIgHgKAAQgMAAgHAMQgGALAAARQgBAQAKANQAJANAMAAQAJAAAFgCQAGgCAFgEIAFgDQAFgEAEAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgXAAgRgQg");
	this.shape_7.setTransform(-3.6,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgXBRIgPgBIgJAAIgJABQgNAAgFgCQgFgCAAgFQABgEAFgCQAHgDABgBQABgCABgRIABgrIgBgpQgBgRgBgCQgBgCgHgCQgFgDgBgEQABgFAEgCQAFgCANAAIAKABIALAAIAPgBIANAAQApAAAXAWQAWAVAAAnQABAngYAUQgXAUgsAAgAgXg/QgGACgBADQgBAFgBANIgBAiIABAqQABARABAEQABADAIADQAHACAKAAQAZAAANgQQAMgPAAgfQAAghgOgRQgPgSgbAAQgJAAgEACg");
	this.shape_8.setTransform(-18.2,0.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgkAqQgPgQAAgYQAAgZAQgRQARgRAYAAQAVAAANAMQAMAMAAAVQAAAHgCACQgCADgHAAIgrAAQgDAAgDgCQgCgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQADgBADAAIAXAAIAFgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgLgGgIQgIgHgKAAQgNAAgGAMQgGALAAARQgBAQAKANQAIANANAAQAJAAAGgCQAFgCAFgEIAFgDQAFgEAEAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgXAAgRgQg");
	this.shape_9.setTransform(-38.8,2.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAQBQQgGgBAAgFQAAgEAGgCIAEgCQACgCACgEIABgRQAAgkgFgIQgFgJgLAAQgFAAgGAEQgFADgDAGQgDAEgBAIIAAAfIAAAPQABAEADABIAEACQAGACAAAEQAAAFgGABQgFACgPAAQgRAAgGgCQgFgBAAgFQAAgEAFgCIADgBQADgCACgFIABgRIAAgSIAAgRIgBgyQgBgNgBgCQgCgBgGgCQgHgCAAgEQAAgDADgCIANgGIALgDIAKgBQAEAAABACQACACAAAFIAAAFIgBAtIAAAFIAAADIACABIACgDIAEgFQAGgFAGgDQAGgDAHABQATAAAJAMQAKANAAAXIAAALIAAAUIAAAHQAAAFABACQABADADACIACABQAGABAAAFQAAAFgFABQgGACgRAAQgPAAgFgCg");
	this.shape_10.setTransform(-51.5,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgFBEQgGgCgEgEQgEgEgBgGQgCgGAAgRIAAg7IgKAAIgDgBIgBgDIAAgDQAAgDALgKIAFgEIAEgEQAMgKAEAAIADABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAUIAZAAIAEABQAAABAAAAQAAABABAAQAAABAAAAQAAABAAABIAAACIgBAFQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgXAAIgCABIAAACIAAA3QAAAPACADQACAEAHAAQAEAAAFgCIAIgCQAAAAABAAQABAAAAAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAFgJAGQgKAGgMAAQgGAAgFgBg");
	this.shape_11.setTransform(-61.9,1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thedesserts, new cjs.Rectangle(-67.9,-15.3,135.8,30.6), null);


(lib.the = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgkAqQgQgQAAgYQAAgZARgRQAQgRAZAAQAWAAAMAMQAMAMABAVQAAAHgCACQgDADgHAAIgrAAQgEAAgCgCQgCgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQACgBAEAAIAWAAIAGgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgLgIgIQgHgHgKAAQgNAAgGAMQgHALABARQAAAQAJANQAIANANAAQAJAAAGgCQAFgCAGgEIADgDQAHgEACAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgYAAgQgQg");
	this.shape.setTransform(10.5,2.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AAQBQQgGgBAAgFQAAgEAGgCIAEgCQACgCACgEIABgRQAAgkgFgIQgFgJgLAAQgFAAgGAEQgFADgDAGQgDAEgBAIIAAAfIAAAPQABAEADABIAEACQAGACAAAEQAAAFgGABQgFACgPAAQgRAAgGgCQgFgBAAgFQAAgEAFgCIADgBQADgCACgFIABgRIAAgSIAAgRIgBgyQgBgNgBgCQgCgBgGgCQgHgCAAgEQAAgDADgCIANgGIALgDIAKgBQAEAAABACQACACAAAFIAAAFIgBAtIAAAFIAAADIACABIACgDIAEgFQAGgFAGgDQAGgDAHABQATAAAJAMQAKANAAAXIAAALIAAAUIAAAHQAAAFABACQABADADACIACABQAGABAAAFQAAAFgFABQgGACgRAAQgPAAgFgCg");
	this.shape_1.setTransform(-2.2,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgFBEQgGgCgEgEQgEgEgBgGQgCgGAAgRIAAg7IgKAAIgDgBIgBgDIAAgDQAAgDALgKIAFgEIAEgEQAMgKAEAAIADABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAUIAZAAIAEABQAAABAAAAQAAABABAAQAAABAAAAQAAABAAABIAAACIgBAFQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgXAAIgCABIAAACIAAA3QAAAPACADQACAEAHAAQAEAAAFgCIAIgCQAAAAABAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAFgJAGQgKAGgMAAQgGAAgFgBg");
	this.shape_2.setTransform(-12.6,1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.the, new cjs.Rectangle(-18.6,-15.3,37.2,30.6), null);


(lib.potatoesholidaymains = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.largemobileholidaymainspotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-45.5,-19);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.potatoesholidaymains, new cjs.Rectangle(-45.5,-19,91,38), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AARAjIgRg4IgQA4IgKAAIgVhFIAKAAIAQA3IAQg3IAKAAIARA3IAQg3IAKAAIgVBFg");
	this.shape.setTransform(26.2,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGAkIgIgCQgGgCgFgFQgGgGgCgHQgDgGAAgIQAAgIADgGQACgHAGgEQAFgFAGgDIAIgCIAGgBQAIAAAHADIAGADIAFAFQAGAEACAHQADAGAAAIQAAAIgDAGQgCAHgGAGIgFAEIgGADQgHADgIAAIgGgBgAgKgZQgFACgEAEIgEAJQgCAFAAAFQAAAGACAFQACAFADAEQADAEAFACQAFACAFAAQAGAAAFgCQAFgCAEgEQADgEABgFQACgFAAgGQAAgFgCgFQgBgFgDgEQgEgEgFgCQgFgDgGAAQgFAAgFADg");
	this.shape_1.setTransform(17.1,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARAjIgkg4IAAA4IgKAAIAAhFIANAAIAkA3IAAg3IAKAAIAABFg");
	this.shape_2.setTransform(9.1,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AANAjIgQgfIgLAAIAAAfIgKAAIAAhFIAXAAIAIABQAFABADACQAEADABAEQADADAAAGQgBAHgFAFIgFADIgGACIATAggAgOgEIALAAIAFAAIAFgCIAEgEIACgEIgCgGIgDgDIgFgCIgFgBIgMAAg");
	this.shape_3.setTransform(0.2,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWAjIAAhFIAsAAIAAAJIgiAAIAAAUIAgAAIAAAIIggAAIAAAYIAjAAIAAAIg");
	this.shape_4.setTransform(-5.9,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeAjIAAhFIAYAAQAGAAAHACQAHACAEAEQAGAEADAHIADAIIABAHIgBAJIgDAGIgDAHIgGAFQgEAEgHACIgNACgAgUAbIAMAAQAGgBAFgCQAFgBAEgDQAEgEACgFIACgFIAAgGIAAgFIgCgGQgCgFgEgDIgJgFQgFgBgGAAIgMAAg");
	this.shape_5.setTransform(-12.6,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AANAjIgQgfIgLAAIAAAfIgKAAIAAhFIAXAAIAIABQAFABADACQADADACAEQACADABAGQgBAHgFAFIgFADIgGACIATAggAgOgEIALAAIAFAAIAGgCIADgEIABgEIgBgGIgDgDIgFgCIgFgBIgMAAg");
	this.shape_6.setTransform(-19.3,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHAkIgHgCQgGgCgGgFQgEgGgEgHQgCgGAAgIQAAgIACgGQAEgHAEgEQAGgFAGgDIAHgCIAHgBQAIAAAHADIAGADIAFAFQAFAEADAHQADAGAAAIQAAAIgDAGQgDAHgFAGIgFAEIgGADQgHADgIAAIgHgBgAgKgZQgFACgEAEIgFAJQgCAFAAAFQAAAGACAFQADAFADAEQADAEAFACQAFACAFAAQAGAAAFgCQAFgCADgEQAEgEACgFQABgFAAgGQAAgFgBgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgFAAgFADg");
	this.shape_7.setTransform(-26.8,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-33.1,-8.1,66.3,16.2), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.logokale = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(130.4,59.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(62.2,30.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(81.2,88.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(52.4,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(22.6,88.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-11.1,88.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-44.3,88.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-78.1,88.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(14.6,-54.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-21,30.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-98.4,30.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(110.1,30.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-74.6,-36.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(69.2,-37.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(114.4,-37.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-175,-175,350,350);


(lib.holidaymainsgreens = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.largemobileholidaymainsgreens();
	this.instance.parent = this;
	this.instance.setTransform(-37.5,-37);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsgreens, new cjs.Rectangle(-37.5,-37,75,74), null);


(lib.holidaymainscranberries = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.largemobileholidaymainscranberries();
	this.instance.parent = this;
	this.instance.setTransform(-39,-21);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscranberries, new cjs.Rectangle(-39,-21,78,42), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("A4wnfMAxhAAAIAAO/MgxhAAAg");
	this.shape.setTransform(0,0,1.006,1.031);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-160.5,-50.5,321,101), null);


(lib.ctarectanglevideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AmGBPIAAidIMNAAIAACdg");
	this.shape.setTransform(0,0,1.101,1.406);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectanglevideo, new cjs.Rectangle(-43,-11.1,86.1,22.3), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AmtBvIAAjdINbAAIAADdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-43,-11.1,86,22.3), null);


(lib.cinnamonrollssymbol = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.largemobileholidaymainscinnamonbunstwo();
	this.instance.parent = this;
	this.instance.setTransform(-56.5,-60);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cinnamonrollssymbol, new cjs.Rectangle(-56.5,-60,113,120), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.ctarollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// Layer 1
	this.instance = new lib.ctarectanglevideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43,-11.1,86.1,22.3);


// stage content:
(lib.largemobileholidaymains = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_32 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_228 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(32).call(this.frame_32).wait(196).call(this.frame_228).wait(7));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.7,50.2,1.558,0.155,0,0,0,0.2,1.3);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(235));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(160,50);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(235));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(161.2,50.5,1.954,0.168,0,0,0,0.4,0.3);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.2,scaleX:1.95,scaleY:0.17,x:160.3,y:50,alpha:0},9).wait(226));

	// logo
	this.instance_2 = new lib.logokale("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(280.6,21.6,0.163,0.163,0,0,0,0.3,0.3);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({regX:0,regY:0,scaleX:0.01,scaleY:0.01,x:269,y:29.6},0).to({regX:2.5,regY:1.1,scaleX:0.22,scaleY:0.22,x:269.4,y:29.8,alpha:1},6).to({regX:1.2,regY:1,scaleX:0.21,scaleY:0.21,x:269.2},7,cjs.Ease.get(1)).wait(213));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AzGI3IAAxtMAo3AAAIAARtg");
	mask.setTransform(139.3,43.3);

	// well-make-the-feast
	this.instance_3 = new lib.wellmakethefeastuse();
	this.instance_3.parent = this;
	this.instance_3.setTransform(69.5,28.2);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(191).to({x:-70.5},0).to({x:74.5,alpha:1},10,cjs.Ease.get(1)).to({x:69.5},6,cjs.Ease.get(1)).wait(28));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AzGI3IAAxtMAo3AAAIAARtg");
	mask_1.setTransform(139.3,43.3);

	// YOU-TAKE-THE-CREDIT
	this.instance_4 = new lib.wellmakethefeast();
	this.instance_4.parent = this;
	this.instance_4.setTransform(79,60.3);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(206).to({x:-66},0).to({x:84,alpha:1},10,cjs.Ease.get(1)).to({x:79},6,cjs.Ease.get(1)).wait(13));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AzGI3IAAxtMAo3AAAIAARtg");
	mask_2.setTransform(139.3,43.3);

	// well-make
	this.instance_5 = new lib.wellmakeuse();
	this.instance_5.parent = this;
	this.instance_5.setTransform(84.8,23.5);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(22).to({x:-70.2},0).to({x:89.8,alpha:1},10,cjs.Ease.get(1)).to({x:84.8},6,cjs.Ease.get(1)).wait(141).to({alpha:0},5).wait(51));

	// the
	this.instance_6 = new lib.the();
	this.instance_6.parent = this;
	this.instance_6.setTransform(35.7,48.5);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(59).to({alpha:1},0).wait(120).to({alpha:0},0).wait(56));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("AzGI3IAAxtMAo3AAAIAARtg");
	mask_3.setTransform(139.3,43.3);

	// the-turkey
	this.instance_7 = new lib.theturkeyuse();
	this.instance_7.parent = this;
	this.instance_7.setTransform(77.8,48.5);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(22).to({x:-77.2},0).to({x:82.8,alpha:1},10,cjs.Ease.get(1)).to({x:77.8},6,cjs.Ease.get(1)).wait(21).to({alpha:0},5).wait(171));

	// the-desserts
	this.instance_8 = new lib.thedesserts();
	this.instance_8.parent = this;
	this.instance_8.setTransform(85,48.5);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(139).to({alpha:1},10).wait(30).to({alpha:0},5).wait(51));

	// the Sides.t
	this.instance_9 = new lib.thesides();
	this.instance_9.parent = this;
	this.instance_9.setTransform(68.9,48.5);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(99).to({alpha:1},10).wait(30).to({alpha:0},5).wait(91));

	// the-stuffing
	this.instance_10 = new lib.thestuffing();
	this.instance_10.parent = this;
	this.instance_10.setTransform(81,48.5);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(59).to({alpha:1},10).wait(30).to({alpha:0},5).wait(131));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("AxlI3IAAxtMAnWAAAIAARtg");
	mask_4.setTransform(139.3,43.3);

	// order-now
	this.instance_11 = new lib.ordernow();
	this.instance_11.parent = this;
	this.instance_11.setTransform(59.9,81.7);
	this.instance_11.alpha = 0;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(32).to({x:-47.4},0).to({x:64.9,alpha:1},10,cjs.Ease.get(1)).to({x:59.9},6,cjs.Ease.get(1)).wait(187));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("AzGI3IAAxtMAo3AAAIAARtg");
	mask_5.setTransform(139.3,43.3);

	// cta-rollover
	this.cta_rollover = new lib.ctarollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(60.1,81.9);

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(32).to({x:-47.4,alpha:0},0).to({x:65.1,alpha:1},10,cjs.Ease.get(1)).to({x:60.1},6,cjs.Ease.get(1)).wait(187));

	// mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	mask_6.graphics.p("AzGI3IAAxtMAo3AAAIAARtg");
	mask_6.setTransform(139.3,43.3);

	// cta-rectangle
	this.instance_12 = new lib.ctarectangle();
	this.instance_12.parent = this;
	this.instance_12.setTransform(60.1,81.8);
	this.instance_12.alpha = 0;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(32).to({x:-47.4},0).to({x:65.1,alpha:1},10,cjs.Ease.get(1)).to({x:60.1},6,cjs.Ease.get(1)).wait(187));

	// greens
	this.instance_13 = new lib.holidaymainsgreens();
	this.instance_13.parent = this;
	this.instance_13.setTransform(282.5,63);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(32).to({alpha:1},10).wait(193));

	// cranberries
	this.instance_14 = new lib.holidaymainscranberries();
	this.instance_14.parent = this;
	this.instance_14.setTransform(214,79);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(27).to({alpha:1},10).wait(198));

	// cinnamon-buns-two
	this.instance_15 = new lib.cinnamonrollssymbol();
	this.instance_15.parent = this;
	this.instance_15.setTransform(225.5,2);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(22).to({alpha:1},10).wait(203));

	// potatoes
	this.instance_16 = new lib.potatoesholidaymains();
	this.instance_16.parent = this;
	this.instance_16.setTransform(110.5,81);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(17).to({alpha:1},10).wait(208));

	// table
	this.instance_17 = new lib.largemobileholidaymainstable();
	this.instance_17.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(235));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(159.9,-8,321,159);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 100,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;